### ISSUE TITLE
commits not increasing pr is increasing

### ISSUE THREAD

**Issue by savagecarol** [kossiitkgp/kwoc-bugs#29] opened 2021-01-01 09:58 UTC
## Description of the Issue
my pr is increased but commit is not increasing

![image](https://user-images.githubusercontent.com/56194329/103436835-06c61a80-4c46-11eb-9861-b1cc83be6530.png)
and i have more commits
*

**Comment by rakaar** [comment] 2021-01-04 11:37
Hey @savagecarol 
Commits are counted only after the PR is merged in the default branch of the project repo. That is the data obtained from Github API.

**Comment by savagecarol** [comment] 2021-01-04 11:56
![image](https://user-images.githubusercontent.com/56194329/103532816-e8645700-4eb1-11eb-8adb-2e02229784ae.png)
it is merged

**Comment by rakaar** [comment] 2021-01-04 12:10
@savagecarol 
The issue is that the PR is not merged in the default branch. Can you please ask the mentor to change the default branch, so that the stats can be included.

**Comment by savagecarol** [comment] 2021-01-04 12:17
Okay

**Closed** 2021-01-04 12:20 UTC
