### ISSUE TITLE
duplicate project

### ISSUE THREAD

**Issue by Blackcipher101** [kossiitkgp/kwoc-bugs#5] opened 2020-12-01 16:23 UTC
## Description of the Issue
My project was added twice whereas I added only once

* URL:https://kwoc.kossiitkgp.org/dashboard/mentor
* Date Observed:1/12/2020

**Comment by yashrsharma44** [comment] 2020-12-02 13:47
Hey did you fill the form once and submit? Or any issues happened on the way?

**Comment by yashrsharma44** [comment] 2020-12-02 13:53
Hey, were you able to submit your project in one go? Or did you face any issues in between?

**Comment by rakaar** [comment] 2020-12-05 10:55
Duplicate of `CamSanx` project has been removed. Hence closing the issue

**Closed by rakaar** 2020-12-05 10:55 UTC
